AllDays/MVCCourse/Demo/Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Day2.Models
{
    public class Instructor
    {
        public int id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public decimal salary { get; set; }
        public string address { get; set; }
        [ForeignKey("Department")]
        public int Department_id { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}

AllDays/MVCCourse/Demo/Controllers/InstructorController.cs
using Day2.interfaces;
using Day2.Models;
using Day2.repository;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Day2.Controllers
{
    public class InstructorController : Controller
    {
        private readonly IGenericRepo<Department> departmentRepo;
        private readonly IGenericRepo<Course> courseRepo;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly BL.BLInstructor bLInstructor;

        public InstructorController(
            IGenericRepo<Department> _departmentRepo,
            IGenericRepo<Course> _courseRepo,
            IWebHostEnvironment _webHostEnvironment,
            BL.BLInstructor _bLInstructor
            )
        {
            departmentRepo = _departmentRepo;
            courseRepo = _courseRepo;
            webHostEnvironment = _webHostEnvironment;
            bLInstructor = _bLInstructor;
        }
        public IActionResult GetAll()
        {
            var all2 = bLInstructor.GetAll();
            return View(all2);
        }
        public IActionResult Details(int id)
        {
            var s = bLInstructor.GetByID(id);
        
            return View(s);
        }
        public IActionResult Delete(int id)
        {
            var s = bLInstructor.GetByID(id);

            return View(s);
        }
        [HttpPost]
        public IActionResult Delete(int id,Instructor instructor)
        {
            bLInstructor.Delete(id);
            return RedirectToAction(nameof(GetAll));
        }
        public IActionResult Edit(int id)
        {
          //ViewData["DropDown"] = departmentRepo.GetAll().Select(a => new {id = a.id , name= a.name}).ToList();
            ViewData["DropDown"] = departmentRepo.GetAll().ToList();
            var m2 = bLInstructor.GetByID(id);
            return View(m2);
        }
        [HttpPost]
        public IActionResult Edit(InstructorViewModel model)
        {
            var instru = bLInstructor.GetByIDNoTracking(model.id);

            string filename = string.Empty;
            if (model.file != null)
            {
                string uploads = Path.Combine(hostingEnvironment.WebRootPath, "image");
                filename = model.file.FileName;
                string fullpath = Path.Combine(uploads, filename);

                string oldfilename = instru.image;
                string fulloldpath = Path.Combine(uploads, oldfilename);
          
                if (fullpath != oldfilename)
                {
                    System.IO.File.Delete(fulloldpath);
                    model.file.CopyTo(new FileStream(fullpath, FileMode.Create));
                }
                instru.image = filename; 
            }

            bLInstructor.Update(instru);
            return RedirectToAction(nameof(GetAll));
        }
        [HttpGet]
        public IActionResult Create()
        {
            var model = new InstructorViewModel
            {
                Departments = departmentRepo.GetAll().ToList()
            };

            // ViewData["DropDown"] = departmentRepo.GetAll().Select(a => new {id = a.id , name= a.name}).ToList();
            //ViewData["DropDown"] = departmentRepo.GetAll().ToList();
            return View(model);
        }
        [HttpPost]
        public IActionResult Create(InstructorViewModel model)
        {
            string filename = string.Empty;
            if(model.file !=null)
            {
               
                string uploads = Path.Combine(hostingEnvironment.WebRootPath, "image");
                filename = model.file.FileName;
                string fullpath = Path.Combine(uploads, filename);
                model.file.CopyTo(new FileStream(fullpath,FileMode.Create));
                model.image = filename;

            }

            bLInstructor.Insert(model);
            return RedirectToAction(nameof(GetAll));
        }
    }
}

AllDays/MVCCourse/Demo/Controllers/TraineeController.cs
using Day2.interfaces;
using Day2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Day2.Controllers
{
    public class TraineeController : Controller
    {
        private readonly IGenericRepo<Trainee> traineeRepo;
        private readonly IGenericRepo<Course> courseRepo;
        private readonly IGenericRepo<CourseResult> courseResultRepo;

        public TraineeController(IGenericRepo<Trainee> _traineeRepo , IGenericRepo<Course> _courseRepo, IGenericRepo<CourseResult> _courseResultRepo)
        {
            traineeRepo = _traineeRepo;
            courseRepo = _courseRepo;
            courseResultRepo = _courseResultRepo;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ShowResult(int student_id,int course_id)
        {
           var course = courseRepo.GetByID(course_id);
            var courseresult = courseResultRepo.GetAll()
                .Where(a => a.Course_id == course_id && a.Trainee_id == student_id)
                .Include(s => s.Trainee).Include(c => c.Course).Select(x =>
                                new CourseResultViewModel
                                {
                                course_id = x.Course_id,
                                studentname = x.Trainee.name,
                                coursename = x.Course.name,
                                degree = x.degree,
                                color = "red"

                                }).FirstOrDefault();
            if (courseresult.degree >= course.mindegree)
            {
                courseresult.color = "green";
            }
            return View(courseresult);
        
        }
        public IActionResult ShowCourseResult()
        { 
          var courseresult = courseResultRepo.GetAll().Include(s=>s.Trainee).
                Include(c=>c.Course).Select(x =>
            new CourseResultViewModel
          {
                course_id=x.Course_id,
              studentname = x.Trainee.name,
              coursename = x.Course.name,
              degree = x.degree,
          }).ToList();

            for (int i = 0; i < courseresult.Count(); i++)
            {
                var course = courseRepo.GetByID(courseresult[i].course_id);
                courseresult[i].mindegree = course.mindegree;
                if (courseresult[i].degree >= course.mindegree)
                {
                    courseresult[i].color = "green";
                }
                else
                {
                    courseresult[i].color = "red";
                }
            }
           
            return View(courseresult);

        }
    }
}

AllDays/MVCCourse/Demo/Views/Instructor/Create.cshtml
@model Day2.InstructorViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Instructor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="file" class="control-label"></label>
                <input asp-for="file" name="file" type="file" class="form-control" />
                <span asp-validation-for="image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="salary" class="control-label"></label>
                <input asp-for="salary" class="form-control" />
                <span asp-validation-for="salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                <select asp-for="Department_id" class="form-control" 
                        
                        asp-items="@(new SelectList(Model.Departments,"id","name"))"> </select>
                <span asp-validation-for="Department_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAll" class="btn btn-outline-primary">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AllDays/MVCCourse/Demo/Views/Instructor/Delete.cshtml
@model Day2.InstructorViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            <img src="~/image/@Model.image" style="width:100px;height:100px;" class="card-img-top" alt="...">
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="GetAll" class="btn btn-outline-primary">Back to List</a>
    </form>
</div>

AllDays/MVCCourse/Demo/Views/Instructor/Details.cshtml
@model Day2.InstructorViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>GetByIDInstructor</h1>

<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.image)
        </dt>
        <dd class="col-sm-10">
            <img src="~/image/@Model.image" style="width:100px;height:100px;" class="card-img-top" alt="...">
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.salary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.salary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department.name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="GetAll" class="btn btn-outline-primary">Back to List</a>
</div>

AllDays/MVCCourse/Demo/Views/Instructor/Edit.cshtml
@model Day2.InstructorViewModel

@{
    ViewData["Title"] = "Edit";
    SelectList l = new SelectList(ViewBag.DropDown, "id", "name");
}

<h1>Edit</h1>

<h4>Instructor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input readonly asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="image" class="control-label"></label>
                <input asp-for="image" type="file" name="file" class="form-control" />
                <span asp-validation-for="image" class="text-danger"></span>
                <img src="~/image/@Model.image" style="width:145px; height:145px;" class="img-thumbnail" />
            </div>
            <div class="form-group">
                <label asp-for="salary" class="control-label"></label>
                <input asp-for="salary" class="form-control" />
                <span asp-validation-for="salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department_id" class="control-label"></label>
                @*<select asp-for="Department_id" class="form-control"
        asp-items="@(new SelectList(Model.Departments,"id","name"))"> *@
            <select name="Department_id" id="Department_id" class="form-control">

                @foreach(var item in (IEnumerable<Department>) ViewData["DropDown"])
                {
                    @if(Model.Department_id == item.id)
                    {
                        <option value="@item.id" selected>@item.name</option>
                    }
                    else
                    {
                    <option value="@item.id">@item.name</option>
                    }
                }
            </select>
                <span asp-validation-for="Department_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAll" class="btn btn-outline-primary">Back to List</a>ShowResult
    <a asp-action="ShowResult" asp-controller="Trainee" class="btn btn-outline-primary">ShowResult</a>ShowResult
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AllDays/MVCCourse/Demo/Views/Instructor/GetAll.cshtml
@model IEnumerable<Day2.InstructorViewModel>

@{
    ViewData["Title"] = "GetAll";
}

<h1>GetAll</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department.name)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    <img src="~/image/@item.image" style="width:100px;height:100px;" class="card-img-top" alt="...">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.salary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department.name)
                </td>
                <td>

                    @Html.ActionLink("Details", "Details", new { id = item.id }) |
                    @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id }) |
                </td>
            </tr>
        }
    </tbody>
</table>